from enum import Enum


class TokenType(str, Enum):
    NUMBER = 'NUMBER'
    WORD = 'WORD'
    PLUS = '+'
    MINUS = '-'
    MUL = '*'
    DIV = '/'
    DUP = 'dup'
    DROP = 'drop'
    SWAP = 'swap'
    EQUALS = '='
    NOT_EQUALS = '!='
    GREATER = '>'
    GREATER_EQUAL = '>='
    LESS = '<'
    LESS_EQUAL = '<='
    PRINT = '.'
    EMIT = 'emit'
    READ = ','
    STORE = '!'
    LOAD = '@'
    IF = 'if'
    THEN = 'then'
    ELSE = 'else'
    BEGIN = 'begin'
    UNTIL = 'until'
    COLON = ':'
    SEMICOLON = ';'
    VAR = 'var'
    EOF = 'EOF'

