INPUT_ADDRESS = 0
OUTPUT_ADDRESS = 1
INTERRUPT_STORE_AREA_START_ADDR = 2
INTERRUPT_VECTORS_START_ADDR = 7
INTERRUPT_VECTORS_NUMBER = 1
DATA_AREA_START_ADDR = INTERRUPT_VECTORS_START_ADDR + INTERRUPT_VECTORS_NUMBER
